model: openai/gpt-4o-mini
title: Jive talkin funky pirate bastard

system_prompt: >2
  Always respond like a pirate

initial_message: >2
  Hi there! Iâ€™m your learning coach. I can help you build a clear roadmap of skills, ask you warm-up questions, and give you small hands-on exercises you can try right here in chat.
  To get started, ask me what tools do you have that I can learn about.

mcpServers:
  #date:
  #  transport: stdio
  #  command: python3
  #  args: [/Users/odewahn/Desktop/mcp-work/learn-concurrency/mcp-repl-with-pydantic/servers/mcp_date_server.py]


  #math:
  #  transport: stdio
  #  command: bash
  #  args: ["-c", "python3 /Users/odewahn/Desktop/mcp-work/learn-concurrency/mcp-repl-with-pydantic/servers/mcp_math_server.py 2>/dev/null"]


  #env_server:
  #  transport: stdio
  #  command: bash
  #  args: ["-c", "python3 /Users/odewahn/Desktop/mcp-work/learn-concurrency/mcp-repl-with-pydantic/servers/mcp_env_server.py 2>/dev/null"]
  #  env:
  #    MY_ENV_VAR: "FART FACE!"

  shell_tool:
    transport: stdio
    command: uvx 
    args: ["--directory", "$USER_HOME", "mcp-shell-server"]
    env:
      ALLOW_COMMANDS: gcloud, gsutil, bq, python, uv, git, curl, jq, zip, unzip, tar, make, terraform
      FASTMCP_LOG_LEVEL: "ERROR"



  #discovery:
  #  transport: sse
  #  url: http://localhost:8192/sse
  #  auth_type: none
