[project]
name = "astrid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "litellm",
    "rich",
    "art",
    "prompt_toolkit",
]

[project.scripts]
astrid = "astrid.__main__:main"
